
version: '3.3'

services:
  postgres01:
    image: postgres:latest
    container_name: postgres01 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=SeekBar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
    - network
  web:
    build: ./backend
    container_name: backend_web_1
    command: python3 manage.py runserver 0.0.0.0:8001
    depends_on:
      - postgres01
    volumes:
      - ./backend/:/code
    ports:
      - "8001:8001"
    networks:
    - network

  vue:
    container_name: "VueJS_container"
    build: ./frontend/vue-vuex/.
    working_dir: /app
    command: bash -c "npm install && npm run serve"
    ports:
      - "4000:8080"
    volumes:
      - ./frontend/vue-vuex:/app
    depends_on:
      - servidor
    networks:
      - network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "dakiti@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "alex123456789"
    logging:
      driver: "none"
    ports:
      - 6969:80
    depends_on:
      - postgres01
    networks:
      - network

networks:
  network:


      