# Generated by Django 3.1.6 on 2021-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210217_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TextField(blank=True),
        ),
    ]
