# Generated by Django 3.1.6 on 2021-02-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_joined',
        ),
    ]
