# Generated by Django 3.1.6 on 2021-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_bar_reference_booking'),
        ('profiles', '0005_remove_booking_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reference_booking',
            field=models.ManyToManyField(related_name='booking_by', through='profiles.Booking', to='bars.Bar'),
        ),
    ]
