# Generated by Django 3.1.6 on 2021-02-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_bar_reference_booking'),
        ('profiles', '0006_auto_20210217_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('person', 'bar', 'time')},
        ),
    ]
