# Generated by Django 3.1.6 on 2021-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210217_1148'),
        ('bars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='reference_booking',
            field=models.ManyToManyField(through='profiles.Booking', to='profiles.Profile'),
        ),
    ]
